export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERINFO: "SET_USERINFO",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLISTID: "SET_PLAYLISTID",
  SET_TRACK: "SET_TRACK",
};
